# Salaries Around world Dataset 


DS_JOBS_SALARIES_AROUND_WORLD = ["ANALYST", "DATA ENGINEER", "DATA SCIENTIST", "MACHINE LEARNING ENGINEER", "ARCHITECT", "DATA SCIENCE", "DATA ANALYTICS"]
MAP_DS_JOB_SALARIES_AROUND_WORLD = {
    "ANALYST": "DATA ANALYST",
    "DATA ANALYTICS": "DATA ANALYST",
    "DATA SCIENCE": "DATA SCIENTIST",
    "ANALYTICS ENGINEER": "DATA ANALYST",
    "ETL DEVELOPER": "DATA ENGINEER",
    "ARCHITECT" : "DATA ARCHITECT",
    "COMPUTER VISION ENGINEER":"MACHINE LEARNING ENGINEER",
    "DEEP LEARNING ENGINEER":"MACHINE LEARNING ENGINEER",
    "MACHINE LEARNING INFRASTRUCTURE ENGINEER":"MACHINE LEARNING ENGINEER",
    "MACHINE LEARNING SOFTWARE ENGINEER":"MACHINE LEARNING ENGINEER",
    "MACHINE LEARNING DEVELOPER": "MACHINE LEARNING ENGINEER",
    "COMPUTER VISION SOFTWARE ENGINEER": "MACHINE LEARNING ENGINEER",
    "MACHINE LEARNING MANAGER": "MACHINE LEARNING ENGINEER",
    "HEAD OF MACHINE LEARNING" : "MACHINE LEARNING ENGINEER",
    "ML ENGINEER":"MACHINE LEARNING ENGINEER",
    "MLOPS ENGINEER":"MACHINE LEARNING ENGINEER",
    "NLP ENGINEER":"MACHINE LEARNING ENGINEER",
    "AI DEVELOPER": "MACHINE LEARNING ENGINEER",
    "AI SCIENTIST":"RESEACHER",
    "APPLIED SCIENTIST":"RESEACHER",
    "APPLIED MACHINE LEARNING SCIENTIST":"RESEACHER",
    "3D COMPUTER VISION RESEARCHER":"RESEACHER",
    "DEEP LEARNING RESEARCHER":"RESEACHER",
    "MACHINE LEARNING RESEARCH ENGINEER":"RESEACHER",
    "MACHINE LEARNING RESEARCHER":"RESEACHER",
    "RESEARCH ENGINEER":"RESEACHER",
    "RESEARCH SCIENTIST":"RESEACHER",
    "MACHINE LEARNING SCIENTIST": "RESEACHER",
    "HEAD OF DATA": "CHIEF DATA OFFICER",
    "CLOUD DATABASE ENGINEER":"DATABASE ENGINEER"
    
}

MAP_EXPIRIENCE_LEVEL_SALARIES_AROUND_WORLD = {
    "EN": "ENTRY-LEVEL",
    "EX": "EXPIRIENCED",
    "MI": "MID-LEVEL",
    "SE": "SENIOR-LEVEL"
}

MAP_COMPANY_SIZE_SALARIES_AROUND_WORLD = {
    "L": "LARGE-SIZE",
    "M": "MEDIUM-SIZE",
    "S": "SMALL-SIZE",
}

#H1BDATA

MAP_USA_STATES_H1BDATA = {
    "DC 20006": "WA",
    "CA 95134": "CA",
    "WASHINGTON": "WA",
    "VT.": "VT"	,
    "TX 77002": "TX",
    "NJ 07642": "NJ",
    "IL 60654": "IL",
    "SHOREVIEW":"MN",
    "MINNEAPOLIS": "MN",
    "MO 63105":"MO",
    "SAN RAMON,":	"CA",
    "SAN RAMON": "CA",
    "5TH FL": "FL",
    "NEW YORK": "NY",
    'NY,': "NY",
    "ETS DRIVE": "unknown",
    '': "unknown",
    "D.C.":"WA",
    "D.C":"WA",
    "ATLANTA":"GA",
    "LONG ISLAND CITY": "NY"

}

#Job Descriptions 

DS_JOBS_GLASSDOOR_JOB_DESCRIPTION =  ["DATA SCIENTIST","DATA ENGINEER","DATA ANALYST","DATA ARCHITECT","BI ANALYST","BUSINESS ANALYST","STATISTICIAN", "DATA ANALYTICS","DATA SPECIALIST", "DATA SCIENCE","DATA ANALYSIS","ANALYST", "ANALYTICS","DATA MANAGEMENT SPECIALIST","BUSINESS ANALYSIS", "MACHINE LEARNING ENGINEER", "RESEARCH","SOFTWARE ENGINEER","MACHINE LEARNING SCIENTIST","ASSOCIATE SCIENTIST", "DATA MODELER"]


JOB_ROLES_MAP_GLASSDOOR_JOB_DESCRIPTION = {
    "BUSINESS ANALYSIS": "DATA ANALYST",
     "DATA ANALYTICS": "DATA ANALYST",
     "DATA ANALYSIS": "DATA ANALYST",
     "DATA SCIENCE" : "DATA SCIENTIST",
     "ANALYST": "DATA ANALYST",
     "DATA MANAGEMENT SPECIALIST": "DATA SPECIALIST",
     "ANALYTICS":"DATA ANALYST",
     "RESEARCH": "RESEARCHER",
     "MACHINE LEARNING SCIENTIST": "RESEARCHER",
     "DATA ENGINEER I": "DATA ENGINEER",
     "DATA ENGINEER II": "DATA ENGINEER",
     "DATA ENGINEER III": "DATA ENGINEER",
     "DATA ANALYST I":"DATA ANALYST",
     "DATA ANALYST II":"DATA ANALYST",
     "DATA ANALYST III":"DATA ANALYST",
     "DATA ANALYST JUNIOR":"DATA ANALYST",
     "DATA ARCHITECT II": "DATA ARCHITECT",
     "DATA ARCHITECT I": "DATA ARCHITECT",
     "DATA ARCHITECT III": "DATA ARCHITECT",
     "MARKETING DATA ANALYST": "DATA ANALYST",
     "DATA ENGINEER (REMOTE)": "DATA ENGINEER",
     "CLOUD DATA ENGINEER": "DATA ENGINEER",
     "SR. DATA ENGINEER": "DATA ENGINEER",
     "BUSINESS DATA ANALYST	": "DATA ANALYST",
     "SR. DATA ANALYST": "DATA ANALYST",
     "SENIOR MACHINE LEARNING ENGINEER": "MACHINE LEARNING ENGINEER",
     "DATA SCIENTIST (REMOTE)": "DATA SCIENTIST",
     "DATA SCIENTIST I": "DATA SCIENTIST",
     "DATA SCIENTIST II": "DATA SCIENTIST",
     "DATA SCIENTIST III": "DATA SCIENTIST",
     "AWS DATA ENGINEER":"DATA ENGINEER",
     "AZURE DATA ENGINEER":"DATA ENGINEER",
     "DATA SCIENCE ENGINEER":"DATA SCIENTIST",
     "MACHINE LEARNING ENGINEER (IMAGING)": "MACHINE LEARNING ENGINEER",
     "MACHINE LEARNING SCIENTIST":"RESEARCHER"

}